---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- ../../base
- pvc.yaml

patches:
  - target:
      kind: Deployment
      name: triton-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/command
        value:
          - /bin/bash
          - -c
          - |
            #!/bin/bash

            run_sleep(){
              echo "Ponder the universe with infinite sleep..."
              sleep infinity
            }

            tritonserver \
              --model-repository=${MODEL_REPOSITORY:-/models} \
              --model-control-mode=poll \
              --repository-poll-secs=60 || run_sleep
  - target:
      kind: Deployment
      name: triton-server
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1
        value:
          name: models
          persistentVolumeClaim:
            claimName: triton-models-cache
  - path: imagestream.yaml
